FROM gradle:8.5-jdk21 AS builder
WORKDIR /app
COPY build.gradle settings.gradle gradlew ./
COPY gradle ./gradle
COPY SERVICE_NAME ./SERVICE_NAME
RUN gradle :SERVICE_NAME:bootJar --no-daemon

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /app/SERVICE_NAME/build/libs/*.jar app.jar
EXPOSE PORT
ENTRYPOINT ["java", "-jar", "app.jar"]
